.TH CMICS "1" "April 2020" "cmics 2.1.0" "User Commands"
.SH NAME
cmics \- The C based comics downloader
.SH DESCRIPTION
The C based comics downloader
.SS "USAGE:"
.IP
cmics [Vh] [dsr]
.PP
OPTIONS:
.br
\fB\-V\fR, \fB\-\-version\fR                   Print version info and exit
.br
\fB\-h\fR, \fB\-\-help\fR                      Print this  message and exit
.br
\fB\-r\fR, \fB\-\-remove\fR                    Remove comic files by name
.br
\fB\-s\fR, \fB\-\-display\fR                   Display comics by name
.br
\fB\-d\fR, \fB\-\-download\fR                  Download comics by name
.br
\fB\-a\fR, \fB\-\-archive\fR                   Show archive of previous comics
.PP
Omission of any arguments starts an ncurses\-based UI.
.SH COPYRIGHT
Copyright \(co 2020 Barthandelous01
License RBSD 3\-Clause License.
.br
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
